{% set version = "0.14.0" %}

package:
  name: libhidapi
  version: {{ version }}

source:
  url: https://github.com/libusb/hidapi/archive/refs/tags/hidapi-{{ version }}.tar.gz
  sha256: a5714234abe6e1f53647dd8cba7d69f65f71c558b7896ed218864ffcf405bcbd

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('libhidapi', max_pin='x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - cmake
    - pkg-config
    - ninja
  host:
    - libudev  # [linux]
    - libusb  # [linux]

test:
  commands:
    # check that headers get installed
    - test -f $PREFIX/include/hidapi/hidapi.h  # [unix]
    - test -f $PREFIX/include/hidapi/hidapi_libusb.h  # [linux]
    - test -f $PREFIX/include/hidapi/hidapi_darwin.h  # [osx]
    - if not exist %PREFIX%\\Library\\include\\hidapi\\hidapi.h exit 1  # [win]
    - if not exist %PREFIX%\\Library\\include\\hidapi\\hidapi_winapi.h exit 1  # [win]

    # check that libraries get installed
    - test -f $PREFIX/lib/libhidapi-hidraw${SHLIB_EXT}  # [linux]
    - test -f $PREFIX/lib/libhidapi-libusb${SHLIB_EXT}  # [linux]
    - test -f $PREFIX/lib/libhidapi${SHLIB_EXT}  # [osx]
    - if not exist %PREFIX%\\Library\\bin\\hidapi.dll exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\hidapi.lib exit 1  # [win]

about:
  home: https://github.com/libusb/hidapi
  license: BSD-3-Clause OR GPL-3.0-only OR LicenseRef-hidapi
  license_file:
    - LICENSE.txt
    - LICENSE-bsd.txt
    - LICENSE-gpl3.txt
    - LICENSE-orig.txt
  summary: 'A Simple cross-platform library for communicating with HID devices'
  description: >
    HIDAPI is a multi-platform library which allows an application to interface with USB and Bluetooth HID-Class devices on Windows, Linux, FreeBSD, and macOS.

    ## HIDAPI has four back-ends:

        Windows (using hid.dll)
        Linux/hidraw (using the Kernel's hidraw driver)
        libusb (using libusb-1.0 - Linux/BSD/other UNIX-like systems)
        macOS (using IOHidManager)

    On Linux, either the hidraw or the libusb back-end can be used. There are tradeoffs, and the functionality supported is slightly different. Both are built by default. It is up to the application linking to hidapi to choose the backend at link time by linking to either libhidapi-libusb or libhidapi-hidraw.

    Note that you will need to install an udev rule file with your application for unprivileged users to be able to access HID devices with hidapi. Refer to the 69-hid.rules file in the udev directory for an example.

    ### Linux/hidraw (linux/hid.c):

    This back-end uses the hidraw interface in the Linux kernel, and supports both USB and Bluetooth HID devices. It requires kernel version at least 2.6.39 to build. In addition, it will only communicate with devices which have hidraw nodes associated with them. Keyboards, mice, and some other devices which are blacklisted from having hidraw nodes will not work. Fortunately, for nearly all the uses of hidraw, this is not a problem.

    ### Linux/FreeBSD/libusb (libusb/hid.c):

    This back-end uses libusb-1.0 to communicate directly to a USB device. This back-end will of course not work with Bluetooth devices.
  dev_url: https://github.com/libusb/hidapi

extra:
  recipe-maintainers:
    - ryanvolz
